[package]
name = "proto_cross_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "3.0.1"
proto = { path = "../proto"}

[build-dependencies]
cc = "1.0.83"
